module.exports = {
  "af": "Salaam my vriend",
  "ax": "Hej min vän",
  "al": "Përshëndetje mik",
  "dz": "مرحبا صديقي",
  "as": "Talofa la'u uo",
  "ad": "Hola amic meu",
  "ao": "Olá meu amigo",
  "ai": "Hello my bredda",
  "aq": "Hello my friend",
  "ag": "Hello my bredren",
  "ar": "Hola amigo mío",
  "am": "Բարեւ իմ ընկեր",
  "aw": "Bon bini mi amigu",
  "au": "Hello my mate",
  "at": "Hallo mein Freund",
  "az": "Salam dostum",
  "bs": "Hello my buddy",
  "bh": "مرحبا صديقي",
  "bd": "হ্যালো আমার বন্ধু",
  "bb": "Hello my buddy",
  "by": "Прывітанне мой сябар",
  "be": "Hallo mijn vriend",
  "bz": "Hello my bredda",
  "bj": "Bonjour mon ami",
  "bm": "Hello my bredren",
  "bt": "བཀྲ་ཤིས་བདེན་ཆེ་བཞིའི་ཕྱིར།",
  "bo": "Hola mi amigo",
  "ba": "Zdravo moj prijatelju",
  "bw": "Dumela rraagwe",
  "bv": "Hallo my vriend",
  "br": "Olá meu amigo",
  "io": "Hello my friend",
  "bn": "Hai kawanku",
  "bg": "Здравей моят приятел",
  "bf": "Bonjour mon ami",
  "bi": "Bonjour mon ami",
  "kh": "ជំរាបសួរសិស្សរបស់ខ្ញុំ",
  "cm": "Hello my friend",
  "ca": "Hello my friend",
  "cv": "Olá meu amigo",
  "ky": "Hello my friend",
  "cf": "Bonjour mon ami",
  "td": "Salam my friend",
  "cl": "Hola amigo mío",
  "cn": "你好我的朋友",
  "cx": "Hello my friend",
  "cc": "Hello my friend",
  "co": "Hola mi amigo",
  "km": "Bonjour mon ami",
  "cg": "Bonjour mon ami",
  "cd": "Bonjour mon ami",
  "ck": "Kia orana taku hoa",
  "cr": "Hola mi amigo",
  "ci": "Bonjour mon ami",
  "hr": "Bok moj prijatelju",
  "cu": "Hola mi amigo",
  "cy": "Γειά σου φίλε μου",
  "cz": "Ahoj můj přítel",
  "dk": "Hej min ven",
  "dj": "مرحبا صديقي",
  "dm": "Hello my bredren",
  "do": "Hola mi amigo",
  "ec": "Hola amigo mío",
  "eg": "مرحبا صديقي",
  "sv": "Hola mi amigo",
  "gq": "Hola mi amigo",
  "er": "ሰላም መልእክትኽ፡ ካብ ምስረት፡",
  "ee": "Tere minu sõber",
  "et": "ሰላም መልእኽት",
  "fk": "Hello my friend",
  "fo": "Hallo min venn",
  "fj": "Bula my friend",
  "fi": "Hei ystäväni",
  "fr": "Bonjour mon ami",
  "gf": "Bonjour mon ami",
  "pf": "Bonjour mon ami",
  "tf": "Hello my friend",
  "ga": "Bonjour mon ami",
  "gm": "Hello my friend",
  "ge": "გამარჯობა ჩემი მეგობრი",
  "de": "Hallo mein Freund",
  "gh": "Hello my friend",
  "gi": "Hello my friend",
  "gr": "Γειά σου φίλε μου",
  "gl": "Aluu my friend",
  "gd": "Hello my bredren",
  "gp": "Bonjour mon ami",
  "gu": "Hello my friend",
  "gt": "Hola mi amigo",
  "gg": "Hello my friend",
  "gn": "Bonjour mon ami",
  "gw": "Olá meu amigo",
  "gy": "Hello my friend",
  "ht": "Bonjour zanmi mwen",
  "hm": "Hello my friend",
  "va": "Hello my friend",
  "hn": "Hola mi amigo",
  "hk": "你好我的朋友",
  "hu": "Helló barátom",
  "is": "Halló vinur minn",
  "in": "नमस्ते मेरो साथी",
  "id": "Halo temanku",
  "ir": "سلام دوست من",
  "iq": "مرحبا صديقي",
  "ie": "Hello my friend",
  "im": "Hello my friend",
  "il": "שלום חבר שלי",
  "it": "Ciao amico mio",
  "jm": "Hello my bredren",
  "jp": "こんにちは私の友人",
  "je": "Hello my friend",
  "jo": "مرحبا صديقي",
  "kz": "Сәлем досым",
  "ke": "Hujambo rafiki yangu",
  "ki": "Mauri my friend",
  "kr": "안녕하세요 제 친구",
  "kw": "مرحبا صديقي",
  "kg": "Салам устам",
  "la": "ສະບາຍດີ my friend",
  "lv": "Sveiki mans draugs",
  "lb": "مرحبا صديقي",
  "ls": "Hello my friend",
  "lr": "Hello my friend",
  "ly": "مرحبا صديقي",
  "li": "Hallo my friend",
  "lt": "Labas mano drauge",
  "lu": "Moien my friend",
  "mo": "嗨我的朋友",
  "mk": "Здраво мој пријател",
  "mg": "Manahoana my friend",
  "mw": "Moni my friend",
  "my": "Hello my kawan",
  "mv": "ދިވެހިންނަށް މި ކަނޑު",
  "ml": "Hello my friend",
  "mt": "Hello my friend",
  "mh": "Yokwe my friend",
  "mq": "Hello my friend",
  "mr": "مرحبا صديقي",
  "mu": "Hello my friend",
  "yt": "Hello my friend",
  "mx": "Hola my friend",
  "fm": "Hello my friend",
  "md": "Salutare prietenul meu",
  "mc": "Bonjour mon ami",
  "mn": "Сайн байна уу миний найз",
  "me": "Zdravo moj prijatelju",
  "ms": "Hello my bredren",
  "ma": "مرحبا صديقي",
  "mz": "Olá meu amigo",
  "mm": "ဟယ်လို ကောင်းသူ",
  "na": "Hello my friend",
  "nr": "Hello my friend",
  "np": "नमस्कार मेरो साथी",
  "nl": "Hallo mijn vriend",
  "an": "Hallo my vriend",
  "nc": "Bonjour mon ami",
  "nz": "Hello my friend",
  "ni": "Hola mi amigo",
  "ne": "Bonjour mon ami",
  "ng": "Hello my friend",
  "nu": "Fakalofa atu my friend",
  "nf": "Hello my friend",
  "mp": "Hello my friend",
  "no": "Hei min venn",
  "om": "مرحبا صديقي",
  "pk": "ہیلو میرے دوست",
  "pw": "Alii my friend",
  "ps": "مرحبا صديقي",
  "pa": "Hola mi amigo",
  "pg": "Hello my friend",
  "py": "Hola mi amigo",
  "pe": "Hola my friend",
  "ph": "Kamusta kaibigan ko",
  "pn": "Hello my friend",
  "pl": "Cześć mój przyjacielu",
  "pt": "Olá meu amigo",
  "pr": "Hola my friend",
  "qa": "مرحبا صديقي",
  "re": "Hello my friend",
  "ro": "Salut prietenul meu",
  "ru": "Привет мой друг",
  "rw": "Hello my friend",
  "bl": "Bonjour my friend",
  "sh": "Hello my friend",
  "kn": "Hello my friend",
  "lc": "Hello my friend",
  "mf": "Bonjour my friend",
  "pm": "Hello my friend",
  "vc": "Hello my friend",
  "ws": "Talofa my friend",
  "sm": "Ciao my friend",
  "st": "Olá my friend",
  "sa": "مرحبا صديقي",
  "sn": "Bonjour mon ami",
  "rs": "Здраво мој пријатељ",
  "sc": "Hello my friend",
  "sl": "Hello my friend",
  "sg": "Hello my friend",
  "sk": "Ahoj môj priateľ",
  "si": "Pozdravljen moj prijatelj",
  "sb": "Hello my friend",
  "so": "Hello my friend",
  "za": "Hello my friend",
  "gs": "Hello my friend",
  "es": "Hola my friend",
  "lk": "හෙලෝ මගේ යහපත්",
  "sd": "مرحبا صديقي",
  "sr": "Hallo mijn vriend",
  "sj": "Hallo my friend",
  "sz": "Hello my friend",
  "se": "Hej min vän",
  "ch": "Hallo my friend",
  "sy": "مرحبا صديقي",
  "tw": "你好我的朋友",
  "tj": "Салом дусти",
  "tz": "Hello my friend",
  "th": "สวัสดีเพื่อนของฉัน",
  "tl": "Hello my friend",
  "tg": "Bonjour mon ami",
  "tk": "Kia orana my friend",
  "to": "Malo e lelei my friend",
  "tt": "Hello my friend",
  "tn": "مرحبا صديقي",
  "tr": "Merhaba arkadaşım",
  "tm": "Salam dostum",
  "tc": "Hello my friend",
  "tv": "Hello my friend",
  "ug": "Hello my friend",
  "ua": "Привіт мій друг",
  "ae": "مرحبا صديقي",
  "gb": "Hello my friend",
  "us": "Hello my friend",
  "um": "Hello my friend",
  "uy": "Hola mi amigo",
  "uz": "Salom do'stim",
  "vu": "Hello my friend",
  "ve": "Hola my friend",
  "vn": "Xin chào bạn tôi",
  "vg": "Hello my friend",
  "vi": "Hello my friend",
  "wf": "Hello my friend",
  "eh": "مرحبا صديقي",
  "ye": "مرحبا صديقي",
  "zm": "Hello my friend",
  "zw": "Hello my friend"
}
